services:
  - type: web
    name: vaalentine
    env: docker
    plan: free
    region: ohio
    branch: main
    numInstances: 1
    healthCheckPath: /api/config
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false # Set this manually in Render Dashboard
      - key: EMAIL_USER
        sync: false # Set this manually in Render Dashboard
      - key: EMAIL_PASS
        sync: false # Set this manually in Render Dashboard
      - key: BREVO_API_KEY
        sync: false # Set this manually in Render Dashboard
